config/routes.rb
Rails.application.routes.draw do
  resources :markets, only: [:index, :show]
  resources :vendors, only: [:show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/markets_controller.rb
class MarketsController < ApplicationController
  def index
    @markets = MarketsFacade.new.all_markets
  end

  def show
    @market = MarketsFacade.new.one_market(market_params[:id])
    vendor_ids = @market.vendors_at_market
    @vendors = MarketsFacade.new.vendors(vendor_ids)
  end


  private
  def market_params
    params.permit(:id, :name, :street, :city, :county, :state, :zip, :lat, :lon, :vendor_count, :vendors)
  end
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  def show
    @vendor = MarketsFacade.new.one_vendor(vendor_params[:id])
  end


  private
  def vendor_params
    params.permit(:id, :name, :description, :contact_name, :phone, :credit_accepted)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarketMoneyFe</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/markets/index.html.erb
<h1>Markets</h1><br>

<table>
  <tr>
    <th>Name</th>
    <th>City</th>
    <th>State</th>
    <th> </th>
  </tr>
    <% @markets.each do |market| %>
  <tr>
      <div class="market-<%= market.id %>">
        <td><%= market.name %></td>
        <td><%= market.city %></td>
        <td><%= market.state %></td>
        <td><%= button_to "More Info", market_path(market.id), method: :get %></td>
      </div>
  </tr>
    <% end %>
</table>

app/views/markets/show.html.erb
<h1><%= @market.name %></h1><br>
<h4>
  <%= @market.street %><br>
  <%= "#{@market.city}, #{@market.state} #{@market.zip}" %>
</h4>

<br><br>
<h3>Vendors at our Market:</h3>
<ul>
  <% @vendors.each do |vendor| %>
    <li><%= link_to "#{vendor.name}", vendor_path(vendor.id) %></li>
  <% end %>
</ul>

app/views/vendors/show.html.erb
<h1><%= @vendor.name %></h1>

<br>
<div>
Contact Info:<br>
name: <%= @vendor.contact_name %><br>
phone: <%= @vendor.phone %><br><br>

Credit Accepted? <%= @vendor.credit_accepted? %><br><br>

Description: <%= @vendor.description %><br><br>
</div>